# Generated by Django 3.0.3 on 2020-06-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Local', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
    ]
