# Generated by Django 3.0.3 on 2020-03-29 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=10)),
                ('origem', models.CharField(max_length=200)),
                ('local_coleta', models.CharField(max_length=200)),
                ('data_coleta', models.DateField(default=datetime.date.today)),
                ('tipo_amostra', models.CharField(choices=[('SA', 'Sangue'), ('FE', 'Fezes'), ('FA', 'Resultado do FAMACHA'), ('CA', 'Carrapato'), ('MO', 'Mosca'), ('PU', 'Pulga'), ('PI', 'Piolho'), ('OU', 'Outro')], default='OU', max_length=2)),
            ],
        ),
    ]
