# Generated by Django 3.0.3 on 2020-05-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0008_auto_20200519_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='responsavel',
        ),
    ]
