# Generated by Django 3.0.3 on 2020-05-19 19:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0011_remove_amostra_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='responsavel',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
