# Generated by Django 3.0.3 on 2020-05-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0013_auto_20200519_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='responsavel',
            field=models.CharField(default='User.name', max_length=200),
        ),
    ]
