# Generated by Django 3.0.3 on 2020-05-19 19:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0014_auto_20200519_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='responsavel',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
