# Generated by Django 3.0.3 on 2020-05-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0018_amostra_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='responsavel',
        ),
    ]
