# Generated by Django 3.0.3 on 2020-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0024_auto_20200519_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
