# Generated by Django 3.0.3 on 2020-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0026_amostra_exame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amostra',
            options={'ordering': ['-data_coleta', 'origem', 'local_coleta', 'especie_animal', 'identificacao', 'tipo_amostra']},
        ),
        migrations.AddField(
            model_name='amostra',
            name='localidade',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
