# Generated by Django 3.0.3 on 2020-06-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Local', '0003_local'),
        ('Amostra', '0034_auto_20200607_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='localidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='Local.Local'),
        ),
    ]
