# Generated by Django 3.0.3 on 2020-06-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0035_auto_20200607_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='especie_animal',
            field=models.CharField(choices=[('AV', 'Aves'), ('BO', 'Bovino'), ('CA', 'Camarão'), ('CN', 'Canino'), ('CP', 'Caprino'), ('EQ', 'Equino'), ('FE', 'Felino'), ('PE', 'Peixe'), ('OV', 'Ovino'), ('SU', 'Suíno'), ('OU', 'Outro')], max_length=2),
        ),
    ]
