# Generated by Django 3.0.3 on 2020-06-17 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0040_auto_20200617_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
