# Generated by Django 3.0.3 on 2020-06-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0041_auto_20200617_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='created_at',
        ),
    ]
