# Generated by Django 2.2.5 on 2021-04-13 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0027_delete_realizacaoexame'),
        ('Amostra', '0043_amostra_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='exame',
        ),
        migrations.CreateModel(
            name='RealizacaoExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_numerico', models.IntegerField(null=True)),
                ('resultado_textual', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amostra.Amostra')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exame.Exame')),
            ],
        ),
        migrations.AddField(
            model_name='amostra',
            name='exames',
            field=models.ManyToManyField(through='Amostra.RealizacaoExame', to='Exame.Exame'),
        ),
    ]
