# Generated by Django 3.0.3 on 2020-05-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizacaoExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=200)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exame.Exame')),
            ],
        ),
    ]
