# Generated by Django 3.0.3 on 2020-05-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amostra', '0026_amostra_exame'),
        ('Exame', '0002_realizacaoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacaoexame',
            name='amostra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Amostra.Amostra'),
        ),
    ]
