# Generated by Django 3.0.3 on 2020-06-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0003_realizacaoexame_amostra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exame',
            options={'ordering': ('nome',)},
        ),
        migrations.AddField(
            model_name='exame',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
