# Generated by Django 3.0.3 on 2020-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0004_auto_20200609_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='created_at',
            field=models.DateTimeField(default=' '),
        ),
    ]
