# Generated by Django 3.0.3 on 2020-06-11 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0004_auto_20200609_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
