# Generated by Django 3.0.3 on 2020-06-11 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0006_realizacaoexame_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
