# Generated by Django 3.0.3 on 2020-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0007_realizacaoexame_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
