# Generated by Django 3.0.3 on 2020-06-11 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0007_auto_20200611_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
