# Generated by Django 3.0.3 on 2020-06-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0008_auto_20200610_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='created_at',
        ),
    ]
