# Generated by Django 3.0.3 on 2020-06-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0009_remove_exame_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
