# Generated by Django 3.0.3 on 2020-06-11 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0009_remove_realizacaoexame_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
