# Generated by Django 3.0.3 on 2020-06-11 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0010_realizacaoexame_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
