# Generated by Django 3.0.3 on 2020-06-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0011_auto_20200611_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizacaoexame',
            name='data',
        ),
    ]
