# Generated by Django 3.0.3 on 2020-06-11 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0012_remove_realizacaoexame_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizacaoexame',
            name='created_at',
        ),
        migrations.AddField(
            model_name='realizacaoexame',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
