# Generated by Django 3.0.3 on 2020-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0013_auto_20200611_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='resultado',
            field=models.BigIntegerField(null=True),
        ),
    ]
