# Generated by Django 3.0.3 on 2020-06-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0013_auto_20200610_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
