# Generated by Django 3.0.3 on 2020-06-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0014_auto_20200612_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='tipo_resultado',
            field=models.CharField(choices=[('NUM', 'Numérico'), ('TEX', 'Textual')], default='NUM', max_length=3),
        ),
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_textual', models.CharField(max_length=200)),
                ('resultado_numerico', models.IntegerField()),
                ('ordem', models.PositiveIntegerField()),
                ('exame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='Exame.RealizacaoExame')),
            ],
            options={
                'ordering': ['exame'],
            },
        ),
    ]
