# Generated by Django 3.0.3 on 2020-06-17 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0014_auto_20200612_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
