# Generated by Django 3.0.3 on 2020-06-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0015_auto_20200615_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexame',
            name='exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='Exame.Exame'),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='resultado_numerico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='resultado_textual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
