# Generated by Django 3.0.3 on 2020-06-27 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0015_realizacaoexame_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
