# Generated by Django 3.0.3 on 2020-06-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0015_realizacaoexame_created_at'),
        ('Exame', '0016_auto_20200618_1714'),
    ]

    operations = [
    ]
