# Generated by Django 3.0.3 on 2020-07-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0017_merge_20200627_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizacaoexame',
            name='resultado',
        ),
        migrations.AddField(
            model_name='realizacaoexame',
            name='resultado_numerico',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realizacaoexame',
            name='resultado_textual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='tipo_resultado',
            field=models.CharField(choices=[('NUM', 'Intervalos'), ('TEX', 'Valores exatos')], default='NUM', max_length=3),
        ),
    ]
