# Generated by Django 3.0.3 on 2020-06-27 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0018_auto_20200627_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
