# Generated by Django 3.0.3 on 2020-07-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0019_auto_20200627_2033'),
        ('Exame', '0018_auto_20200702_0138'),
    ]

    operations = [
    ]
