# Generated by Django 3.0.3 on 2020-07-11 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0020_merge_20200710_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='tipo_resultado',
            field=models.CharField(choices=[('NUM', 'Números'), ('TEX', 'Valores exatos')], default='NUM', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='realizacaoexame',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
