# Generated by Django 2.2.5 on 2021-03-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0020_merge_20200710_1534'),
        ('Exame', '0024_auto_20200710_2312'),
    ]

    operations = [
    ]
