# Generated by Django 2.2.5 on 2021-03-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0025_merge_20210312_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
