# Generated by Django 2.2.5 on 2021-04-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exame', '0026_auto_20210312_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealizacaoExame',
        ),
    ]
